version: "3.5"
services:
  ng-service:
    container_name: ng
    build: .
    volumes:
      - ".:/usr/src/app"
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
     selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    expose: 
      - 4444
  chrome:
    image: selenium/node-chrome-debug:3.141.59-yttrium
    container_name: chrome
    deploy:
      replicas: 5
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-yttrium
    container_name: firefox
    deploy:
      replicas: 8
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444