trigger:
- workflow-for-deploy

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '15.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g @angular/cli
    ng build --prod
    ng test --sourceMap=false --browsers=ChromeHeadless --watch=false
  displayName: 'npm install and build'
